theme: minima

title: tenzin-io.github.io
description: tenzin-io
author: "tenzin"

base_url: /tenzin-io
repository: tenzin-io/tenzin-io.github.io

# Minima: show excerpts in the frontpage
show_excerpts: True

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
